### ISSUE TITLE
vue-cli如何去debug

### ISSUE THREAD

**Issue by xxholly32** [KuangPF/vue-cli-analysis#1]
我看了写cli没有相应的命令

但代码中有相关的debug

请问下这块是如何debug的？

还有它测试用例是如何跑的？

**Comment by KuangPF** [comment]
1.在分析代码的时候如果需要进行断点调试的话可以使用 `vscode` 内置的 `debug` 调试功能。
2.`@vue/cli` 源码中相关的 `debug` 其实是使用的 npm [debug](https://github.com/visionmedia/debug) 包进行一些 `debug` 信息的输出，例如在 `@vue/cli/lib/Creator.js` 有以下 `debug` 代码：
``` js
resolveFinalPrompts () {
  // come code ...
  const prompts = [
   this.presetPrompt,
   this.featurePrompt,
   ...this.injectedPrompts,
   ...this.outroPrompts
 ]
 debug(' vue-cli:prompts')(prompts)
 return prompts
}
```
执行命令：
``` bash
DEBUG=vue-cli:prompts vue create demo
```
就会输出以下 debug 信息：

![vue-cli-debug-prompts](https://user-images.githubusercontent.com/20694238/51074086-ac78cb80-16b5-11e9-8eaa-e00a78e81c80.png)

3. 在分析源码的过程中有时候也会通过 `console.log()` 输出一些重要的信息来进行调试。
4. 执行 `@vue/cli` 测试用例的 `npm script `在 [@vue/cli test](https://github.com/vuejs/vue-cli/blob/dev/package.json) 中，执行 `npm run test` 即可，`@vue/cli` 的测试用例在 `@vue/cli/__tests__` 文件夹中。

**Comment by xxholly32** [comment]
感谢回复，看了debug仓库学到了一些知识

对于debug来说，个人之前也是用vscode的插件方式去做的，但命令行的继续输入无法做到；

我保证跑完命令只能用 vue create -d demo，所以配置如下

![qq 20190113103341](https://user-images.githubusercontent.com/6063358/51080944-a4ee0c80-171f-11e9-8822-80787f72b784.png)

thx anyway
