### ISSUE TITLE
请问下：vue是如何实现使用vue create xxx 命令行到顶部的？

### ISSUE THREAD

**Issue by Blubiubiu** [KuangPF/vue-cli-analysis#15]

**Comment by KuangPF** [comment]
在执行 `create` 命令是触发了 `clearConsole` 函数
https://github.com/KuangPF/vue-cli-analysis/blob/9b57391efc4e16bc275b1b027edcf4921cf01330/packages/%40vue/cli/lib/create.js#L37

`clearConsole` 实现如下：
https://github.com/KuangPF/vue-cli-analysis/blob/9b57391efc4e16bc275b1b027edcf4921cf01330/packages/%40vue/cli-shared-utils/lib/logger.js#L57

**Comment by Blubiubiu** [comment]
谢谢，昨天找了半天没找到clearconsole里的实现
