### ISSUE TITLE
 vue ui GUI界面点击运行的时候怎么执行的vue-cli-service serve命令？

### ISSUE THREAD

**Issue by wait-hua** [KuangPF/vue-cli-analysis#2]
vue ui GUI界面点击运行后，没看到有发送请求到 server端，告诉server端运行vue-cli-service serve命令，这个client 端和 server端是通过什么方式通信的？

**Comment by KuangPF** [comment]
在 client 端点击运行后，大致流程如下：
vue ui 中  serve 命令的 client 端部分代码目录为 `@vue/cli-ui/src/components/task/ProjectTaskDetails.vue`

``` vue
<VueButton
    v-if="task.status !== 'running'"
    icon-left="play_arrow"
    class="primary"
    :label="$t('org.vue.views.project-task-details.actions.play')"
    data-testid="run-task"
    @click="runTask()"
 />

  <VueButton
    v-else
    icon-left="stop"
    class="primary"
    :label="$t('org.vue.views.project-task-details.actions.stop')"
    data-testid="stop-task"
    @click="stopTask()"
  />
```

`runTask()` 方法

```js
methods: {
    runTask() {
      this.$apollo.mutate({
        mutation: TASK_RUN,
        variables: {
          id: this.id
        }
      })
    },
  }
```

`runTask` 使用 `this.$apollo.mutate()` 来发送一个 GraphQL 变更， apollo 服务端对 TASK_RUN 进行处理。apollo 服务端利用 cli3  [vue-cli-plugin-apollo](https://github.com/Akryum/vue-cli-plugin-apollo) 插件实现，该插件还可以自动将  [vue-apollo](https://github.com/Akryum/vue-apollo) 集成在` vue` 的应用程序中，其他支持的功能可以自行查看。

启动服务端时，入口文件为` vue-cli-plugin-apollo/graphql-server/index.js`，主要作用就是利用 `apollo-server-expres`s 启动一个服务，`apollo-server-express` 是由 Apollo 提供在 express 环境下实现 GraphQL 的库。在这里面会定义一些 resolvers ，来处理 GraphQL 的 query，mutate 或者 subscriptions。

``` js
const resolvers = load(options.paths.resolvers) // GraphQL resolvers
```

所有的 resolvers 在` @vue/cli-ui/apollo-server/resolvers.js`中进行解析，可以看一下比较核心的代码：

```js
// Load resolvers in './schema'
const paths = globby.sync([path.join(__dirname, './schema/*.js')])
paths.forEach(file => {
  const { resolvers: r } = require(file)
  r && resolvers.push(r)
})
```

再看一下 `./schema`目录下面的文件

<img width="277" alt="resolvers-vue-ui" src="https://user-images.githubusercontent.com/20694238/63483955-95fae400-c4d0-11e9-84dd-488a555486b2.png">

这里面就包含了整个` vue ui` 中操作的 `resolvers`，相当于就是当 client 端发出了一下动作，可以是 query，mutate 或者 subscriptions，在 server 端进行对应的操作。那么就以点击` runTask` 按钮为例，来简单看下。首先在` task.js` 中 `Mutation` 如下：

```js
Mutation: {
    taskRun: (root, { id }, context) => tasks.run(id, context),
    taskStop: (root, { id }, context) => tasks.stop(id, context),
    taskLogsClear: (root, { id }, context) => tasks.clearLogs(id, context),
    taskOpen: (root, { id }, context) => tasks.open(id, context),
    taskSaveParameters: (root, { id }, context) => tasks.saveParameters({ id }, context),
    taskRestoreParameters: (root, { id }, context) => tasks.restoreParameters({ id }, context)
  },
```

我们可以很容易定位到 `taskRun`，处理 `taskRun` 的代码在 `cli-ui/apollo-server/connectors/tasks.js`中：

``` js
async function run (id, context) {
  const task = findOne(id, context)
  if (task && task.status !== 'running') {
    // ...
    const child = execa(command, args, {
      cwd: cwd.get(),
      stdio: ['inherit', 'pipe', 'pipe'],
      shell: true
    })

    if (typeof nodeEnv !== 'undefined') {
      process.env.NODE_ENV = nodeEnv
    }

    task.child = child

    const outPipe = logPipe(queue => {
      addLog({
        taskId: task.id,
        type: 'stdout',
        text: queue
      }, context)
    })
    // ...
  }
}
```

比较核心的就是执行了以下代码

```js
execa(command, args, {
  cwd: cwd.get(),
  stdio: ['inherit', 'pipe', 'pipe'],
  shell: true
})
```

首先会根据 `id` 在 `taskMap` 中找到对应的 `taskRun` 的那一项，然后在获取对应的 command，并做一些兼容处理，最后就执行 command，taskRun 对应执行的命令就是:

``` bash
vue-cli-service serve
```

这样当在 `client` 端 `task` 面板中点击 `run` 按钮时实质就执行了` vue-cli-service serve` 命令。

**Comment by wait-hua** [comment]
学习了，大佬，感谢
