### ISSUE TITLE
[Question] 请问作者对 vue-cli 怎么保证生成模版的测试这方面了解吗？

### ISSUE THREAD

**Issue by fireairforce** [KuangPF/vue-cli-analysis#22]
每次在使用 vue-cli 生成模版的时候，怎么保证这些模版能正常工作呢？ 是通过怎么样的测试呢？

**Comment by KuangPF** [comment]
这些模板使用过 [service](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-service/generator) 插件生成的，模版生成逻辑方面有 [test](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-service/__tests__) 规格。如果说如何保证模板正常工作，其实不是太了解，个人看法应该是先写了一套模板，保证其准确性，然后在此基础上添加 esj 等语法。

**Comment by fireairforce** [comment]
我看了下 vue-cli 的 template，比较简单...也没有使用太多复杂的 ejs 语法，应该只用保证生成模版的代码逻辑正确性(即unit测试)，然后再保证生成模版能够正常运行起来(这一步用的 e2e 测试)。
