### ISSUE TITLE
关于vue-cli源码在create时里面的事件有一点不明白

### ISSUE THREAD

**Issue by sq-github** [KuangPF/vue-cli-analysis#4]
您好，请问一下，this.emit('creation', { event: 'creating' }) 像这样提交的事件，没有找到在哪里有接收的地方。

**Comment by KuangPF** [comment]
在使用 `vue ui` 命令创建项目的时候会监听到。
https://github.com/KuangPF/vue-cli-analysis/blob/243647da89b9423d1aba988b5e6702dc3a9ac5e1/packages/%40vue/cli-ui/apollo-server/connectors/projects.js#L100

**Comment by sq-github** [comment]
好的 找到了 十分感谢。 也谢谢博主的源码分享，虽然还有很多没看明白，正在研究中。
