### ISSUE TITLE
你好，我想问一下vue ui界面获取到的那些信息是通过什么获取的呢

### ISSUE THREAD

**Issue by 792472461** [KuangPF/vue-cli-analysis#5]
GraphQL和apollo-server我的理解只是一个服务端和客户端通信的东西，点击项目启动的时候，我看到有一个socket长链接，这个是apollo-server建立的吗，点击启动这个又运行了哪些东西呢

**Comment by KuangPF** [comment]
点击运行项目实质就是执行了 `vue-cli-service serve` 命令，可参考 #2
