### ISSUE TITLE
[Question] 针对Vue cli加载插件模块的一点疑惑

### ISSUE THREAD

**Issue by Viggo95** [KuangPF/vue-cli-analysis#8]
**首先感谢你的分享给我阅读源码时提供的帮助**

## Background
vue cli加载插件模块使用的是自建的loadModule，而不是直接使用require。
这个点在源代码中频繁出现，但是大家似乎都没分析过这个点，个人很好奇为什么vue cli一定要自己实现一遍
[在cli-service中加载模块的代码示例](https://github.com/vuejs/vue-cli/blob/efbc20c67616e116b6d82dadbebd3e5eb768f00d/packages/%40vue/cli-service/lib/Service.js#L191-L200
)
![image](https://user-images.githubusercontent.com/22092110/75124197-8f039700-56e8-11ea-9ed6-41269e047fe6.png)
   
[loadModule具体实现的源码路径](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-shared-utils/lib/module.js#L63-L70)
![image](https://user-images.githubusercontent.com/22092110/75124245-fde0f000-56e8-11ea-810d-d7392fb99d08.png)
   
[sodatea 提交 Pr的issue](https://github.com/vuejs/vue-cli/pull/5092)

      
       
<br>

## Question
我个人初期看到的时候觉得没必要自己去实现require，包括去看了`NodeJs Module模块createRequire、createRequireFromPath`的说明，也并没有看到需要自己去实现的一个必要性，但是其实这个函数贯穿了插件模块使用的全流程，让人比较困惑
    
想咨询一下您对【loadModule】部分的看法，以及是否有必要自建require
       
      
<br>

## 建议
你可以在README中贴一下`alipay`或者`wechat pay`的地址，或许我可以请你喝杯咖啡

<br>
<br>

**Comment by KuangPF** [comment]
这一点其实我也不是很熟悉，不过从代码中的信息可以看出应该有以下几个原因：

* `require.resolve` 在不同上下中解析依赖的时候会存在一定的问题
* `createRequire` 是从不同上下文解析模块的唯一语义正确的方法
* 自定义的 `createRequire` 方法兼容了不同版本的 node 版本，并做对应的处理

如果有更好的答案，欢迎大佬来回答。

最后很感谢能够有想法请我喝一杯咖啡☕️https://github.com/KuangPF/vue-cli-analysis/commit/5fa2b9747930a48a7ebe64042c588b6e36b6ab73

**Comment by Viggo95** [comment]
好的，感谢你的回复
你的回答在思路上解答了我的一些问题，请喝咖啡是应该的
另外这个issue我暂时先不关，等确认之后或者这几天没结论我再来关

**Comment by Viggo95** [comment]
目前我个人的结论是，`loadModule`主要提供了一种相对于第二个参数输入的上下文进行依赖包解析的能力，比如其在[@vue/cli-plugin-eslint/index.js](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-eslint/index.js#L6-L11)这部分
     
![image](https://user-images.githubusercontent.com/22092110/75305170-50084980-5880-11ea-93f4-6d8159916197.png)

      
利用`loadModule`相对引用这一特性，可以做到优先使用用户配置的`eslint`，如果业务没配置再使用内置的`eslint`
      
[社区中关于这一点的详细pr](https://github.com/vuejs/vue-cli/pull/2560)

**Comment by KuangPF** [comment]
@screetBloom 解析的到位
